# Generated by Django 4.0.6 on 2024-06-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0006_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cartelera.pais'),
        ),
    ]
