# Generated by Django 4.0.6 on 2024-06-25 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0009_director_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='foto',
        ),
    ]
