databases:
  - name: servidorMichael
    plan: free
    databaseName: dbcine
    user: michael

services:
  - type: web
    plan: free
    name: cineUTC
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cineUTC.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorMichael
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: cinemichael.onrender.com



# set DATABASE_URL=postgresql://michael:69oedtNSipBv7Apv9bylzoLZ6Yq2WPIr@dpg-cqlpkho8fa8c73bgsbp0-a.oregon-postgres.render.com/dbcine_v7et