"""
Django settings for cineUTC project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
#IMPORTACION DE CODIGOS PARA SUBIR A LA WEB OJO
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i35nc8q=qj-28y--k4_o7t0$zn@023i#th(9kf=_6^2n0cavd*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'cinemichael.onrender.com').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Aplicaciones.Cartelera',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', #lo que se agrego
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cineUTC.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cineUTC.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

#ESTO LO COMENTAMOS POR QUE VAMOS A CAMBIAR A BDD POSTGRESS (subida a web)

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': 'bddCineUTC.db',
#     }
# }

#CODIGO PARA BDD 
DATABASES = {
    # 'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'))
    'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

#CONFIGURACION DE LA CARPETA PARA GESTIONAR ARCHIVOS ESTÁTICOS
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') #SE AGREGA AQUI EN ESTE ORDEN
STATICFILES_DIRS= (os.path.join(BASE_DIR,'cineUTC/static'),)

# VALIDACION
if not DEBUG:
    STATICFILES_ROOT = os.path.join(BASE_DIR,'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

#CONFIGURACION DE LA CARPETA PARA GESTIONAR ARCHIVOS ESTÁTICOS
MEDIA_URL='/media/'
MEDIA_ROOT=(os.path.join(BASE_DIR,'cineUTC/media')) #borrar o poner coma final

#SI ESQUE NO FUNCIONA PARA MOSTRAR IMAGEN VAMOS A HACER ESTO (no morstrar como tupla quitar parentesis y quedaria asi)
#MEDIA_ROOT=os.path.join(BASE_DIR,'cineUTC/media') #borrar o poner coma final



#CONFIGURADOR DE SERVIDOR SMTP

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'llumiugsimichael@gmail.com'
EMAIL_HOST_PASSWORD = 'ougz obpn rocr rple'
DEFAULT_FROM_EMAIL ='llumiugsimichael@gmail.com'

#ultima linea
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
